padding: 1
end: ""
divider: ""
fg: "magenta"
bg: ""
lines_above: 1
modules:
- type: exitcode
  failure_bg: 'red'
  failure_fg: '#45475a'
  show_success: true
  success_bg: 'white'
  success_fg: '#45475a'
  success_output: " "
  failure_output: " "
  padding_before: 0
  padding_after: 0
- type: duration
  bg: '#45475a'
  fg: '#b4befe'
  label: "羽%s"
  threshold: 3s
- type: cwd
  bg: 'blue'
  fg: '#45475a'
  label: " %s"
  separator: "/"
  max_depth: 2
  deep_prefix: "..."
- type: git
  bg: 'yellow'
  fg: '#313244'
- type: command
  bg: '#45475a'
- type: languages
  bg: '#45475a'
- type: text
  text: ""
- type: newline
  padding_before: 0
  padding_after: 0
- type: text
  padding_after: 0
  text: ""
