[".config/nvim"]
    type = "archive"
    url = "https://github.com/NvChad/NvChad/archive/main.tar.gz"
  # waiting for https://github.com/twpayne/chezmoi/issues/1614#issuecomment-966524408
  # exact: true
    stripComponents = 1
    refreshPeriod = "168h"

[".config/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"

[".config/zsh/plugins/zsh-sudo/zsh-sudo.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh"
    refreshPeriod = "168h"

[".config/zsh/plugins/zsh-asdf/zsh-asdf.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/asdf/asdf.plugin.zsh"
    refreshPeriod = "168h"

[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    refreshPeriod = "168h"
    [".asdf".pull]
        args = ["--branch", "v0.10.2"]
    [".asdf".clone]
        args = ["--branch", "v0.10.2"]