linux_display_server x11

#font_family      FiraCode Nerd Font
font_family      JetBrainsMono Nerd Font
font_size 15

#  "Nerd Fonts - Material Design Icons"
# symbol_map U+f500-U+fd46 Symbols Nerd Font

disable_ligatures never

url_style curly

# Windows
map opt+enter new_window_with_cwd
map opt+w close_window

map opt+left neighboring_window left
map opt+right neighboring_window right
map opt+up neighboring_window up
map opt+down neighboring_window down

map opt+r move_window_backward
map opt+shift+r move_window_forward

# Tabs
map opt+shift+t new_tab_with_cwd
map opt+shift+w close_tab

map opt+tab next_tab
map opt+shift+tab previous_tab

# Full screen
map opt+shift+z toggle_layout stack

map cmd+w no_op

# Delete word backward
map cmd+backspace send_text all \x17

# Word navigation
map cmd+left send_text all \x1bb
map cmd+right send_text all \x1bf

cursor_shape beam
cursor_beam_thickness 1.8
window_padding_width 20

mouse_hide_wait 3.0
detect_urls yes
open_url_with /usr/bin/open

repaint_delay 10
input_delay 3
sync_to_monitor yes

tab_bar_style               powerline
tab_bar_edge                bottom
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

background_opacity 0.95

hide_window_decorations titlebar-only
#shell zsh

macos_quit_when_last_window_closed yes

# BEGIN_KITTY_THEME
# Catppuccin-light-tanx
include current-theme.conf
# END_KITTY_THEME
