linux_display_server x11

#font_family      FiraCode Nerd Font
font_family      JetBrainsMono Nerd Font
font_size 14

#  "Nerd Fonts - Material Design Icons"
# symbol_map U+f500-U+fd46 Symbols Nerd Font

disable_ligatures never

url_style curly

map cmd+shift+left neighboring_window left
map cmd+shift+right neighboring_window right
map cmd+shift+up neighboring_window up
map cmd+shift+down neighboring_window down

map cmd+shift+enter new_window_with_cwd
map cmd+shift+d close_window
map cmd+t new_tab_with_cwd
map cmd+d close_tab

map cmd+shift+z toggle_layout stack

cursor_shape beam
cursor_beam_thickness 1.8
window_padding_width 20

mouse_hide_wait 3.0
detect_urls yes

repaint_delay 10
input_delay 3
sync_to_monitor yes

tab_bar_style               powerline
tab_bar_edge                bottom
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

background_opacity 0.95

hide_window_decorations titlebar-only
#shell zsh

macos_quit_when_last_window_closed yes

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
